#!/bin/bash

if [[ -e /etc/debian_version && `which apt-get` ]] &>/dev/null ; then
  echo "<<<apt>>>"
  if [[ -e /var/run/apt-dater-host_reboot ]]; then echo "yes"; else echo "no"; fi
  cat /etc/debian_version
  waitmax 25 /usr/bin/apt-get -o Debug::NoLocking=yes -s dist-upgrade -y | awk '/^Inst/ { print $2 " " $5}' || echo "timeout_apt_get Debian-Security:X.X/DUMMY)"
fi
