#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
#
# Karsten Schoeke <karsten.schoeke@geobasis-bb.de>
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.


import json, sys, urllib2

server = "api.ssllabs.com"
uri = "api/v2/analyze"
proxy = ''

try:
    host_address = sys.argv[1]
    ssl_host_address = sys.argv[2]
    timeout = float(sys.argv[3])
    if len(sys.argv) > 4:
        proxy = sys.argv[4]
except:
    print "Usage: agent_ssllabs <hostname> <ssl_hostname> <timeout> <proxy>"
    sys.exit(2)

#url for request webservice
url = 'https://%s/%s?host=%s&publish=off&all=on&fromCache=On&maxAge=24' % (server, uri, ssl_host_address)

try:
    if proxy != '': 
        https_proxy = urllib2.ProxyHandler({'https': proxy})
        opener = urllib2.build_opener(https_proxy)
        urllib2.install_opener(opener)

    jsonData = json.load(urllib2.urlopen(url, None, timeout))

except urllib2.HTTPError as e:
    print e
    sys.exit(2)

print "<<<<%s>>>>" % host_address
print "<<<ssllabs_grade>>>"

try:
    if jsonData['status'] == "READY":
        print "%s  %s  %s" % (ssl_host_address, jsonData['endpoints'][0]['grade'], jsonData['testTime'])
    if jsonData['status'] == "ERROR":
        print "%s  %s  %s" % (ssl_host_address, jsonData['statusMessage'], jsonData['testTime'])
    if jsonData['status'] == "IN_PROGRESS" or jsonData['status'] == "DNS":
        print "%s  %s  %s" % (ssl_host_address, jsonData['statusMessage'], jsonData['testTime'])

except (ValueError, KeyError, TypeError):
    print "JSON format error"

print "<<<<>>>>"
