#!/usr/bin/python
# Jabber (using ejabberd)

import os, sys, xmpp

fromjid = 'nagios@local'
passwd = '*****'
tojid= os.environ['NOTIFY_CONTACTIM']

message = os.environ['NOTIFY_HOSTNAME'] + " "
max_len = 160

if os.environ['NOTIFY_WHAT'] == 'SERVICE':
    message += os.environ['NOTIFY_SERVICESTATE'][:2] + " "
    avail_len = max_len - len(message)
    message += os.environ['NOTIFY_SERVICEDESC'][:avail_len] + " "
    avail_len = max_len - len(message)
    message += os.environ['NOTIFY_SERVICEOUTPUT'][:avail_len]

else:
    message += "is " + os.environ['NOTIFY_HOSTSTATE']

jid = xmpp.protocol.JID(fromjid)
client = xmpp.Client(jid.getDomain(), debug=[])
client.connect(server=('server.local',5222), use_srv=False)
client.auth(jid.getNode(), passwd)
client.sendInitPresence()
msg = xmpp.Message(tojid, message)
msg.setAttr('type', 'chat'
client.send(msg)
