#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
#
# 2014 Karsten Schoeke karsten.schoeke@geobasis-bb.de

# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

###### FW data
# "1.3.6.1.4.1.2620.1.5.5.0";   # "yes"
# "1.3.6.1.4.1.2620.1.5.6.0";   # "active" / "standby"
# "1.3.6.1.4.1.2620.1.5.7.0";   #"OK" : ha blocking state
# "1.3.6.1.4.1.2620.1.5.102.0"; # "OK" : ha status

def inventory_cp_ha_status(info):
    if len(info) > 0:
        return [ (None, None) ]

def check_cp_ha_status(_no_item, _no_params, info):
    state = 0
    message = ""
    if len(info) > 0:
        message = "node is %s " % info[0][1]
        if info[0][0].lower() == "yes":
            message += " and started." 
        else:
            message += " and stoped." 
        if info[0][2].lower() == "ok":
            message += ", blocking state is %s" % info[0][2]
        else:
            message += " , blocking state is %s" % info[0][2]
            state = 2
        if info[0][3].lower() == "ok":
            message += ", ha state is %s" % info[0][2]
        else:
            message += " , blocking state is %s" % info[0][2]
            state = 2


    if message or state:
        yield state, message

check_info['cp_ha_status'] = {
  "inventory_function"  : inventory_cp_ha_status,
  "check_function"      : check_cp_ha_status,
  "service_description" : "CP HA status",
  "has_perfdata"        : False,
  "group"               : "cp_ha_status",
  "snmp_info"           : ( ".1.3.6.1.4.1.2620.1.5", [ "5.0", "6.0", "7.0", "102.0" ] ),
  "snmp_scan_function"  : lambda oid: oid(".1.3.6.1.4.1.2620.1.5.1.0").lower().startswith('high') 
}
