#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
#
# 2014 Karsten Schoeke karsten.schoeke@geobasis-bb.de

# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

#Name     haProblemTable!@#.iso.org.dod.internet.private.enterprises.checkpoint.products.ha.haProblemTable
#OID  .1.3.6.1.4.1.2620.1.5.13
#MIB  CHECKPOINT-MIB
#Syntax   SEQUENCE OF HaProblemEntry

def inventory_cp_ha_problems(info):
    if len(info) > 0:
        return [ (line[0], None) for line in info]

def check_cp_ha_problems(item, _no_params, info):
    state = 0
    message = ""
    for line in info:
        if line[0] == item:
            if line[1].lower() == "ok":
                message = "%s state is %s" % (item, line[1])
            else:
                message = "%s state is %s" % (item, line[1])
                state = 2

    if message or state:
        yield state, message

check_info['cp_ha_problems'] = {
  "inventory_function"  : inventory_cp_ha_problems,
  "check_function"      : check_cp_ha_problems,
  "service_description" : "CP HA %s state",
  "has_perfdata"        : False,
  "group"               : "cp_ha_problems",
  "snmp_info"           : ( ".1.3.6.1.4.1.2620.1.5.13.1", [ "2", "3" ] ),
  "snmp_scan_function"  : lambda oid: oid(".1.3.6.1.4.1.2620.1.5.1.0").lower().startswith('high')
}
