#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
#
# 2014 Karsten Schoeke karsten.schoeke@geobasis-bb.de

# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

###### FW data
# "1.3.6.1.4.1.2620.1.6.103.0"; # "OK" svn status

def inventory_cp_svn_status(info):
    if len(info) > 0:
        return [ (None, None) ]

def check_cp_svn_status(_no_item, _no_params, info):
    state = 0
    message = ""
    if len(info) > 0:
        message = "svn state is"
        if info[0][0].lower() == "ok":
            message += " %s." % info[0][0]
        else:
            message += " %s." % info[0][0]
            state = 2

    if message or state:
        yield state, message

check_info['cp_svn_status'] = {
  "inventory_function"  : inventory_cp_svn_status,
  "check_function"      : check_cp_svn_status,
  "service_description" : "CP SVN status",
  "has_perfdata"        : False,
  "group"               : "cp_svn_status",
  "snmp_info"           : ( ".1.3.6.1.4.1.2620.1.6", [ "103.0" ] ),
  "snmp_scan_function"  : lambda oid: oid(".1.3.6.1.4.1.2620.1.6.1.0").lower().startswith('svn') 
}
